### ISSUE TITLE
Any thoughts on making available via a package manager?

### ISSUE THREAD

**Issue by marclaporte** [PhilippeMarcMeyer/FieldsLinker#18]
Bonjour Philippe,

FieldsLinker and your other libraries are very interesting.

Any thoughts on making them available via package managers, and findable via https://libraries.io/?

We would like to add to Tiki:
https://tiki.org/FLOSS-Web-Application-with-the-most-built-in-features
So our preference would be via Composer / Packagist.org
https://doc.tiki.org/Composer

Thank you and best regards,

Marc

**Comment by PhilippeMarcMeyer** [comment]
I didn't know tiki, that's nice of you to think about me. One day maybe

**Comment by marclaporte** [comment]
Just for the record: doing this will help all projects include FieldsLinker, not just Tiki.

**Comment by PhilippeMarcMeyer** [comment]
you are right. I'll check it. I have never done that so i'll have to learn

**Comment by marclaporte** [comment]
Super. We'll contribute the composer.json  The other repos will be quite similar.

Thanks!

**Comment by marclaporte** [comment]
For the file, we need to indicate the license. For libs like this, it is very common to use MIT.

What do you think?

Thansk!

**Comment by PhilippeMarcMeyer** [comment]
That's perfect !

**Comment by marclaporte** [comment]
Here is: https://github.com/PhilippeMarcMeyer/FieldsLinker/pull/19   and we'll guide you. It's a one-time set up and after, the systems fetch data at each release.

**Comment by PhilippeMarcMeyer** [comment]
I have been very busy lately. What should I do now ?
I have never used composer or tiki
can I help you ?

**Comment by fabiomontefuscolo** [comment]
Hi @PhilippeMarcMeyer 

To make your project installable, we need to register it in https://packagist.org/.

1. Create an account on https://packagist.org/ and link it with Github 
2. Go to https://packagist.org/packages/submit and submit https://github.com/PhilippeMarcMeyer/FieldsLinker project;
3. Go to https://packagist.org/profile/ and copy you API key (hidden by a green box);
4. Then, follow here https://packagist.org/about#how-to-update-packages and do what is written on section "Do not want to log in via GitHub and grant us webhook configuration access?"

These are boring steps and unfortunately, we can't do it, because just the repository owner can do it.

**Comment by PhilippeMarcMeyer** [comment]
the plugin is already on the packagist fabio and you are the maintainer

**Comment by PhilippeMarcMeyer** [comment]
The plugin is now sync with packagist :-)

**Comment by marclaporte** [comment]
Fantastic!  https://packagist.org/packages/philippemarcmeyer/fieldslinker

So if/when you create some releases, they will appear there as well. Until then, we'll use "dev-master"
https://github.com/PhilippeMarcMeyer/FieldsLinker/releases

@fabiomontefuscolo: this is should be deleted:
https://packagist.org/packages/phillipemarkmeyer/fieldslinker
