### ISSUE TITLE
Controlling Color of Lines

### ISSUE THREAD

**Issue by DrShaneBurke** [PhilippeMarcMeyer/FieldsLinker#26]
On the page located https://philippemarcmeyer.github.io/FieldsLinker/index.html?version=0.96#, the instructions say that colours can be re-defined, but I can't find any documentation on how to do this.  In particular what I would like to do is modify this so one-to-many or many-to-one relationships have the same color lines. Thanks in advance, this is a great project!

**Comment by PhilippeMarcMeyer** [comment]
Hello Dr Burke,
Glad to hear from you
As you certainly already figured out, the only thing you can do is redefining the color sheme by passing it a a comma delimeted string to options.handleColor
I didn't think about giving the same color the a one-to-many or many-to-one relationship : so it needs authoring from myself.
What, at the present time, Fieldlinker is doing : count the links et give each a diffrent color in the same order as the colors array and starting over at the beginning of the array once it the last color has be used  (modulo)

Why not ? as an option though because the change of colors is nive to people like me with medium sight !

Thank you for this excelent issue

**Comment by DrShaneBurke** [comment]
I see (no pun intended).  Thanks for the quick response.  I am new to GitHub and don’t quite know how to contribute to projects yet, but I can work on a revision to add this functionality if you think it is worthwhile.

Perhaps a good strategy would be to include some logic in the makeLink function that looks at linksByName, identifies one-to-many and many-to-one relationships, and revises handleColor via changeParameters such that the same color repeats as needed.  Do you see any flaws in that solution before I start working on this?

**Comment by PhilippeMarcMeyer** [comment]
Absolutely : 
I would search for nodes with multi links on column A to B
Same on column B to A
and then for "lonely" nodes with one link
and attribute a color to each
then draw them in that order 

`
let nodes = [
color : myColor,
links : [...]
]
`
Something like that

I would gladly accept your contribution ; clone version 1.00 and summit a Pull request

Looking forward to ear from you

Philippe Meyer

**Comment by PhilippeMarcMeyer** [comment]
Keep me informed please and telle me if you need any help

**Comment by PhilippeMarcMeyer** [comment]
Maybe a Merge request from you one day ?
