### ISSUE TITLE
How to implement FieldsLinker in Dynamic DIV control

### ISSUE THREAD

**Issue by softtechinfo2020** [PhilippeMarcMeyer/FieldsLinker#27]
I need implement FieldsLinker in Dynamic DIV control .Anyone can help me

**Comment by PhilippeMarcMeyer** [comment]
Hello what do you mean by dynamic DIV control ?

**Comment by softtechinfo2020** [comment]
Dynamically I created div tag using jquery then I have implement fields
linker

**Comment by PhilippeMarcMeyer** [comment]
var $control = $('<div></div>');
                 $control 
			.appendTo($whatever)
				.addClass("bonds")
                                .css({ "display": "block" });
   .
 class="bonds"  style="display:block;"
 var  fieldLinks = $control.fieldsLinker("init", options);

**Comment by softtechinfo2020** [comment]
after adding above am getting value always same,
self.$midDiv.width() value is 20
self.$rightDiv.height() values is 0
self.$leftDiv.height() values is 0
when i have changed dyamic div
please refer below screen,
![image](https://user-images.githubusercontent.com/58630781/91823621-1f520400-ec57-11ea-939d-e472ee67c4ae.png)

**Comment by PhilippeMarcMeyer** [comment]
Please give me your code sample and I'll try to sort it out.

Le 1 sept. 2020 10:01, "softtechinfo2020" <notifications@github.com> a
écrit :

after adding above am getting value always same,
self.$midDiv.width() value is 20
self.$rightDiv.height() values is 0
self.$leftDiv.height() values is 0
when i have changed dyamic div
please refer below screen,
[image: image]
<https://user-images.githubusercontent.com/58630781/91823621-1f520400-ec57-11ea-939d-e472ee67c4ae.png>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/PhilippeMarcMeyer/FieldsLinker/issues/27#issuecomment-684531871>,
or unsubscribe

**Comment by PhilippeMarcMeyer** [comment]
Please check if you have the lastest version (1.02) 
This code works : (tested with jquery-3.5.1.)
```
          var $control = $('<div></div>');
          $control 
	      appendTo($("#fieldLinkerZone"))

	var fieldLinks = $control.fieldsLinker("init", options);
```
You need the latest because because it works with a div that has no id attribute and is compatible with jquery-3.5.1
Why do I talk about jquery-3.5.1 ? because the bissue you are talking about (width == 0) make me think about the version before jquery-3.5.1 compatibility.

Best regards

Philip
