### ISSUE TITLE
TypeError: $li.tooltip is not a function

### ISSUE THREAD

**Issue by Jagdeep-Sing** [PhilippeMarcMeyer/FieldsLinker#5]
Hi, I am using FieldsLinker plugin in my project and it is a great plugin to link or map fields between two lists.
Whenever I'm loading it in the browser, it is showing the following error: 

`TypeError: $li.tooltip is not a function`

Can you please have a look at this? @PhilippeMarcMeyer 

Thanks

**Comment by PhilippeMarcMeyer** [comment]
Hello Jagdeep,
Do you use Jquery and bootstrap ?
I use boostrap 3

**Comment by PhilippeMarcMeyer** [comment]
I use tooltip() bootstrap function that's why you get this error : 
But i've jsute make a new version (v 0.86) which works without bootstrap
You won't have nice tooltips but basic "title" tooltips but it will work.
I have also horizontally re-centered the links 
Tell what you think about it please
Cheers

**Comment by Jagdeep-Sing** [comment]
Hi @PhilippeMarcMeyer ,
Thanks for the response.
The error was coming because the order in which I placed jquery & bootstrap was wrong.
Jquery must be before bootstrap.
Re-ordering solved the problem of tooltip error.
After this a new error `popper js is needed` was coming. So we installed popperjs lib using npm and added that in scripts.
reorder: [PROPER REORDER ](https://stackoverflow.com/a/45649668/5894421)
