### ISSUE TITLE
after getLinks call, next draw erases all the drawings (not data)

### ISSUE THREAD

**Issue by flartet** [PhilippeMarcMeyer/FieldsLinker#9]
Hello bonjour,
After a call to getLinks, if you want then to connect 2 new items, all the previous drawings disappear but not the data.
In real life, with an external call + page reload, it can be avoided but with an ajax save() call or during tests, it's a problem. And I am not able to find why.

**Comment by PhilippeMarcMeyer** [comment]
Hello Flartet, thank you for this issue !
the bug was this : in the  action === "getLinks" section 
links = linksByName; // not a copy but a reference to linksByName array in memory 
then it modify the array links deleting the "table" property to return it
By modifiyng links we modify the original array linksByName which becomes corrupted and unable to function.
Thank you for pointing this bug to me :-)
